In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('data/yolo_prediction/All.csv')

In [11]:
df1 = pd.read_csv('data/coco_diff/All.csv')

In [15]:
df1

,Img,num_people,offset,face_avg_ratio,body_avg_ratio,extremities_avg_ratio,num_people_diff,people_size_diff,visibility_diff,offset_diff,total_dif
0,36,1,0.294100,1.000000,1.000000,0.500000,0.500000,0.720162,0.100000,0.294100,0.403566
1,49,6,0.363385,0.233333,0.291667,0.187500,0.857143,0.996770,0.758333,0.363385,0.743908
2,61,3,0.130800,0.000000,0.000000,0.000000,0.750000,0.997873,1.000000,0.130800,0.719668
3,74,6,0.340124,0.000000,0.000000,0.000000,0.857143,0.998416,1.000000,0.340124,0.798921
4,77,5,0.382953,0.200000,0.550000,0.575000,0.833333,0.983026,0.620000,0.382953,0.704828
...,...,...,...,...,...,...,...,...,...,...,...
58878,581886,3,0.357505,0.200000,0.666667,0.416667,0.750000,0.986880,0.616667,0.357505,0.677763
58879,581887,1,0.690295,0.500000,0.250000,0.000000,0.500000,0.990632,0.675000,0.690295,0.713982
58880,581899,3,0.115953,0.133333,0.000000,0.229167,0.750000,0.998169,0.887500,0.115953,0.687905
58881,581900,6,0.510639,0.166667,0.375000,0.364583,0.857143,0.985052,0.731250,0.510639,0.771021
58882,581921,1,0.333505,0.200000,0.750000,0.812500,0.500000,0.954253,0.512500,0.333505,0.575064

In [19]:
df[df['Img_ID']==1900]

      ID  Img_ID  Confidence  x_center  y_center  width  height
18  1900    1900         0.0       NaN       NaN    NaN     NaN

In [18]:
df1[df1['Img']==1900]

,Img,num_people,offset,face_avg_ratio,body_avg_ratio,extremities_avg_ratio,num_people_diff,people_size_diff,visibility_diff,offset_diff,total_dif
189,1900,1,0.254233,0.0,0.0,0.0,0.5,0.994862,1.0,0.254233,0.687274

In [26]:
import cv2
import numpy as np
image = cv2.imread("./imgs/000000001900.jpg")
if np.all(image[..., 0] == image[..., 1]) and np.all(image[..., 1] == image[..., 2]):
    print("L'immagine Ã¨ in scala di grigi (3 canali con valori identici).")
else:
    print("L'immagine Ã¨ a colori (RGB).")

L'immagine Ã¨ in scala di grigi (3 canali con valori identici).